# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_7bN5RcjeyS9iHNKEOMrGkJhMl83ba8

### Tải xuống mô hình
Để ứng dụng Streamlit của bạn hoạt động, bạn cần có tệp mô hình `best_emotion_model.keras`. Nếu bạn chưa có, bạn có thể tải xuống một mô hình đã được đào tạo trước. Dòng mã dưới đây sẽ tải xuống một mô hình mẫu.
"""

# Download the pre-trained model using wget (more robust for Google Drive)
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1G8_oV32vD1r3p5Q043D2fG0wR2e2C1B1' -O best_emotion_model.keras

print("Mô hình 'best_emotion_model.keras' đã được tải xuống.")

"""### Nội dung của `app.py`

Đây là mã nguồn cho ứng dụng Streamlit của bạn. Mã này sẽ được ghi vào tệp `app.py` bởi cell phía dưới và không nên chạy trực tiếp trong notebook.
"""

streamlit_code = '''
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(page_title="Nhận Diện Cảm Xúc", page_icon="😶", layout="centered")

st.title("😶 Nhận Diện Cảm Xúc Khuôn Mặt")
st.markdown("**Mô hình CNN - FER2013**")

# Load mô hình
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model('best_emotion_model.keras')
    return model

model = load_model()

emotions = ['Angry', 'Disgust', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']
emotions_vn = ['Giận dữ', 'Ghê tởm', 'Sợ hãi', 'Vui vẻ', 'Bình thường', 'Buồn bã', 'Ngạc nhiên']

uploaded_file = st.file_uploader("📤 Tải ảnh khuôn mặt lên", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')
    st.image(image, caption="Ảnh gốc", width=350)

    # Tiền xử lý
    img = image.resize((48, 48))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=-1)
    img_array = np.expand_dims(img_array, axis=0)

    # Dự đoán
    with st.spinner("Đang phân tích cảm xúc..."):
        prediction = model.predict(img_array, verbose=0)
        predicted_class = np.argmax(prediction[0])
        confidence = float(prediction[0][predicted_class] * 100)

    col1, col2 = st.columns(2)
    with col1:
        st.success(f"**Cảm xúc:** {emotions[predicted_class]}")
        st.success(f"**Tiếng Việt:** {emotions_vn[predicted_class]}")
    with col2:
        st.info(f"**Độ tin cậy:** {confidence:.1f}%")

    # Biểu đồ
    st.subheader("📊 Xác suất các cảm xúc")
    probs = {emotions[i]: float(prediction[0][i]*100) for i in range(7)}
    st.bar_chart(probs)

st.caption("Phát triển bởi Streamlit + TensorFlow")
'''

with open("app.py", "w") as f:
    f.write(streamlit_code)

print("Streamlit code saved to app.py")

import os

# Create requirements.txt
requirements = '''
streamlit
tensorflow
numpy
pandas
matplotlib
seaborn
kagglehub
Pillow
'''
with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

# Create runtime.txt (specifying Python version)
with open("runtime.txt", "w") as f:
    f.write("python-3.11")

print("requirements.txt and runtime.txt have been created.")

"""Sau khi mô hình và các tệp cấu hình được tạo, bạn có thể chạy lại các ô bên dưới để cài đặt Streamlit, ngrok và khởi động ứng dụng Streamlit, sau đó tạo một URL công khai để truy cập ứng dụng cục bộ."""

import urllib
import time
import os
from pyngrok import ngrok

# --- CẤU HÌNH TẠI ĐÂY ---
# Dán authtoken của bạn vào giữa dấu ngoặc kép dưới đây
NGROK_AUTHTOKEN = "YOUR_NGROK_AUTHTOKEN_HERE"
# -----------------------

# 1. Giải phóng cổng 8501 nếu đang bị chiếm
!fuser -k 8501/tcp

# 2. Chạy Streamlit ngầm
!nohup streamlit run app.py --server.port 8501 > streamlit_logs.txt 2>&1 &
print("Đang khởi động Streamlit...")
time.sleep(5)

# 3. Kiểm tra log nhanh
with open("streamlit_logs.txt", "r") as f:
    print("\n--- Nhật ký Streamlit ---")
    print(f.read())

# 4. Thiết lập ngrok
if NGROK_AUTHTOKEN == "YOUR_NGROK_AUTHTOKEN_HERE" or NGROK_AUTHTOKEN == "":
    print("❌ LỖI: Bạn chưa nhập NGROK_AUTHTOKEN. Hãy lấy token tại https://dashboard.ngrok.com/get-started/your-authtoken")
else:
    try:
        ngrok.kill()
        ngrok.set_auth_token(NGROK_AUTHTOKEN)
        public_url = ngrok.connect(8501)
        print(f"\n🚀 THÀNH CÔNG! Truy cập ứng dụng tại: {public_url}")
    except Exception as e:
        print(f"❌ Lỗi ngrok: {e}")