# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_7bN5RcjeyS9iHNKEOMrGkJhMl83ba8
"""

# Install Streamlit
!pip install streamlit -qq

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(page_title="Nhận Diện Cảm Xúc", page_icon="😶", layout="centered")

st.title("😶 Nhận Diện Cảm Xúc Khuôn Mặt")
st.markdown("**Mô hình CNN - FER2013**")

# Load mô hình
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model('best_emotion_model.keras')
    return model

model = load_model()

emotions = ['Angry', 'Disgust', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']
emotions_vn = ['Giận dữ', 'Ghê tởm', 'Sợ hãi', 'Vui vẻ', 'Bình thường', 'Buồn bã', 'Ngạc nhiên']

uploaded_file = st.file_uploader("📤 Tải ảnh khuôn mặt lên", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')
    st.image(image, caption="Ảnh gốc", width=350)

    # Tiền xử lý
    img = image.resize((48, 48))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=-1)
    img_array = np.expand_dims(img_array, axis=0)

    # Dự đoán
    with st.spinner("Đang phân tích cảm xúc..."):
        prediction = model.predict(img_array, verbose=0)
        predicted_class = np.argmax(prediction[0])
        confidence = float(prediction[0][predicted_class] * 100)

    col1, col2 = st.columns(2)
    with col1:
        st.success(f"**Cảm xúc:** {emotions[predicted_class]}")
        st.success(f"**Tiếng Việt:** {emotions_vn[predicted_class]}")
    with col2:
        st.info(f"**Độ tin cậy:** {confidence:.1f}%")

    # Biểu đồ
    st.subheader("📊 Xác suất các cảm xúc")
    probs = {emotions[i]: float(prediction[0][i]*100) for i in range(7)}
    st.bar_chart(probs)

st.caption("Phát triển bởi Streamlit + TensorFlow")

streamlit_code = """
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(page_title="Nhận Diện Cảm Xúc", page_icon="😶", layout="centered")

st.title("😶 Nhận Diện Cảm Xúc Khuôn Mặt")
st.markdown("**Mô hình CNN - FER2013**")

# Load mô hình
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model('best_emotion_model.keras')
    return model

model = load_model()

emotions = ['Angry', 'Disgust', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']
emotions_vn = ['Giận dữ', 'Ghê tởm', 'Sợ hãi', 'Vui vẻ', 'Bình thường', 'Buồn bã', 'Ngạc nhiên']

uploaded_file = st.file_uploader("📤 Tải ảnh khuôn mặt lên", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')
    st.image(image, caption="Ảnh gốc", width=350)

    # Tiền xử lý
    img = image.resize((48, 48))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=-1)
    img_array = np.expand_dims(img_array, axis=0)

    # Dự đoán
    with st.spinner("Đang phân tích cảm xúc..."):
        prediction = model.predict(img_array, verbose=0)
        predicted_class = np.argmax(prediction[0])
        confidence = float(prediction[0][predicted_class] * 100)

    col1, col2 = st.columns(2)
    with col1:
        st.success(f"**Cảm xúc:** {emotions[predicted_class]}")
        st.success(f"**Tiếng Việt:** {emotions_vn[predicted_class]}")
    with col2:
        st.info(f"**Độ tin cậy:** {confidence:.1f}%")

    # Biểu đồ
    st.subheader("📊 Xác suất các cảm xúc")
    probs = {emotions[i]: float(prediction[0][i]*100) for i in range(7)}
    st.bar_chart(probs)

st.caption("Phát triển bởi Streamlit + TensorFlow")
"""

with open("app.py", "w") as f:
    f.write(streamlit_code)

print("Streamlit code saved to app.py")

# Create requirements.txt
requirements = """
streamlit
tensorflow
numpy
Pillow
"""
with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

# Create runtime.txt (specifying Python version)
with open("runtime.txt", "w") as f:
    f.write("python-3.10.12")

print("requirements.txt and runtime.txt have been created.")

# 1. Install localtunnel using npm
!npm install -g localtunnel

# 2. Get your public IP (needed as a password for the localtunnel tunnel)
import urllib
print("Password/Tunnel Password:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# 3. Run Streamlit in the background
# Make sure app.py and best_emotion_model.keras are in the current folder
!streamlit run app.py &>/dev/null&

# 4. Expose the port 8501 to the web
!lt --port 8501

"""### **Missing Model File: `best_emotion_model.keras`**

The traceback indicates a `ValueError: File not found: filepath=best_emotion_model.keras`. This means the script cannot locate your pre-trained TensorFlow/Keras model file.

**To fix this, please follow these steps:**

1.  **Upload the model file:** Click the folder icon on the left sidebar in Colab to open the file browser. Then, click the "Upload" icon (upward arrow) and select your `best_emotion_model.keras` file from your local machine. Make sure to upload it to the `/content/` directory, or provide the full path if you upload it elsewhere.

2.  **Verify the upload:** After uploading, you should see `best_emotion_model.keras` listed in the file browser.

Once the model file is uploaded, you can re-run the cell `NzduNVCKeI1N`.

### **How to run the Streamlit app in Colab**

The warnings about `missing ScriptRunContext` you saw earlier are expected when trying to execute a Streamlit app directly within a Colab cell, as it's not a typical Streamlit server environment.

To properly run a Streamlit application in Google Colab and interact with it via a web interface, you need to:

1.  **Save your Streamlit code to a Python file:** The code in cell `NzduNVCKeI1N` needs to be saved as a `.py` file (e.g., `app.py`).
2.  **Run the Streamlit app using `streamlit run`:** You'll then execute a shell command to start the Streamlit server.

I can generate the code to do this for you once the model file is uploaded and the code cell `NzduNVCKeI1N` runs without the `ValueError`.
"""