# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLt-TNuK437WvLI7CxUwOPTCNoSQp3lE
"""

pip install pyngrok streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# 
# import streamlit as st
# 
# st.set_page_config(
#     page_title="Ứng dụng Streamlit của bạn",
#     page_icon=":rocket:",
#     layout="centered",
#     initial_sidebar_state="auto",
# )
# 
# st.title('Chào mừng đến với Streamlit trên Google Colab!')
# st.write('Đây là một ứng dụng Streamlit đơn giản.')
# 
# st.header('Hãy thử một số tương tác:')
# 
# name = st.text_input('Bạn tên là gì?')
# if name:
#     st.write(f'Xin chào, {name}!')
# 
# number = st.slider('Chọn một số', 0, 100, 50)
# st.write(f'Bạn đã chọn: {number}')
# 
# option = st.selectbox(
#     'Bạn thích loại trái cây nào?',
#     ('Táo', 'Chuối', 'Cam', 'Dâu Tây')
# )
# st.write(f'Bạn thích: {option}')
# 
# st.subheader('Vẽ biểu đồ đơn giản:')
# import pandas as pd
# import numpy as np
# 
# chart_data = pd.DataFrame(
#     np.random.randn(20, 3), # 20 hàng, 3 cột
#     columns=['a', 'b', 'c']
# )
# 
# st.line_chart(chart_data)

from pyngrok import ngrok
import os

# BƯỚC QUAN TRỌNG: Dán mã token của bạn vào giữa hai dấu ngoặc kép bên dưới
NGROK_AUTH_TOKEN = "YOUR_NGROK_AUTH_TOKEN"

try:
    # Xóa các tunnel cũ nếu có để tránh xung đột
    ngrok.kill()

    # Cấu hình token
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

    # Mở tunnel mới
    public_url = ngrok.connect(8501)
    print(f"--- THÀNH CÔNG ---")
    print(f"Truy cập ứng dụng tại: {public_url}")
    print(f"------------------")

    # Chạy Streamlit ở chế độ nền
    os.system("nohup streamlit run streamlit_app.py --server.port 8501 &")
    print("Streamlit đang khởi động... Đợi khoảng 5s rồi nhấn vào link trên.")

except Exception as e:
    print(f"Lỗi: {e}")
    print("Hãy đảm bảo bạn đã copy đúng token từ trang chủ của ngrok.")